### ISSUE TITLE
Is there plans to support higher iOS versions

### ISSUE THREAD

**Issue by Spidy123222** [hikari-no-yume/touchHLE#118]
I’m asking about if there is plans to support higher iOS versions than ios 4. From what I recall there was 32bit apps that were released above 4 for backward compatibility reasons with older devices. Like need for speed games hot pursuit.

**Comment by ArbestRiAgain** [comment]
I'm pretty sure it will go up to iOS 6 from 2012.

**Comment by Spidy123222** [comment]
> I'm pretty sure it will go up to iOS 6 from 2012.

I would of thought until 32bit died. I wonder if there’s a discord for TouchHLE.

**Comment by hikari-no-yume** [comment]
> I'm pretty sure it will go up to iOS 6 from 2012.

Who told you that? Don't speak confidently about things you don't know. This is your first warning.

**Comment by hikari-no-yume** [comment]
> I’m asking about if there is plans to support higher iOS versions than ios 4.

I'm not sure how to answer this really. The potential future scope of this project is massive. I only say things are “planned” if I think they will be done in the very near future, because I want to keep expectations in check. I expect iPhone OS 3.0 support to be doable, and I know that it gets harder from 3.1 onwards. I haven't done any research into what would be necessary to support later versions.

In any case, I assume that apps get more complex with each year following the release of the App Store, and thus harder to emulate. That's the real challenge. The OS version number is just the first hurdle.
