### ISSUE TITLE
Dragging a supported ipa file from a separate drive onto touchHLE crashes it 

### ISSUE THREAD

**Issue by Tiny-spring** [hikari-no-yume/touchHLE#153]
See video below for an example
https://www.youtube.com/watch?v=-U-Ha4ZIdB0

**Comment by hikari-no-yume** [comment]
Ah, thanks for pointing this out. The problem is most likely that Windows runs touchHLE in a different "current directory" depending on where you drag the file from.

Since there's an app picker now, I guess I'll just remove all the mentions of dragging stuff onto touchHLE from the README. If you want to be able to do it still, you can create a shortcut to touchHLE (e.g. on the desktop), and make sure the current directory in the shortcut is set to the same directory as touchHLE.exe,

**Comment by SRC267** [comment]
No wonder Flappy Bird was crashing for me the other day.
