### ISSUE TITLE
a fresh IMPROVEMENT to the TouchHLE

### ISSUE THREAD

**Issue by Thetouchedjoe** [hikari-no-yume/touchHLE#169]
yeah I guess, I'm seeing the looks of the app's splahscreen, I feel that the app PNG look so bland and not interactive at all, so yeah Circlized the app icon and when you insert a new game the app splahscreen is bouncing, when you open, there's the game's background with a button says 'start' and yeah the game suddenly run :) like the PSVita but with iPhone's look

From : Me (the idea of the emulator)
To : (every single contributor of this emulator)

**Comment by Thetouchedjoe** [comment]
yeah also is maybe possible to add support to iPod Clickwheel games? So yeah we can play iPod games on the go on Newer devices :)

**Comment by hikari-no-yume** [comment]
> yeah I guess, I'm seeing the looks of the app's splahscreen, I feel that the app PNG look so bland and not interactive at all

The launch image depends entirely on the app. I don't think whether it's “bland” is any of our concern, it is authentic. Also, it only appears for a few seconds at most. It doesn't need to be interactive.

> Circlized the app icon

iOS app icons are meant to be rounded squares. Using a circle would ruin them. I'm not going to do this.

> yeah also is maybe possible to add support to iPod Clickwheel games?

The iPod does not run iOS, so that would require a completely different project.

**Comment by Thetouchedjoe** [comment]
Ok though cause like some app icon are round, if it circle it like one of the areas is cutted so like ruin the experience

**Comment by Thetouchedjoe** [comment]
like for iPod games, it maybe can possibly run like force mount the game to the emulator, but yeah I think the game performance is auto crashed caused of a diffrent OS
