### ISSUE TITLE
Add support for opening IPA files

### ISSUE THREAD

**Issue by upintheairsheep** [hikari-no-yume/touchHLE#20]
Please add support for opening IPA files directly, using the 7zip or a normal zip engine to extract it and run it.

**Comment by hikari-no-yume** [comment]
Ah, yeah, it'd be good to do this at some point! I think someone familiar with Rust can probably figure out how to do it by modifying `fs.rs` to use a zip file library, and return some type like `Box<dyn Read + Write + Seek + …>` instead of `File`. Some small changes in `main.rs` and `bundle.rs` would be needed too.

**Comment by hikari-no-yume** [comment]
Though if anyone does attempt this: please try to pick a ZIP file library that doesn't have tons of dependencies. Keeping the number of dependencies low is a somewhat arbitrary goal but it's a principle I stick to.

**Comment by DCNick3** [comment]
Sounds fun, I'll try to tackle it

**Comment by hikari-no-yume** [comment]
@DCNick3 kindly contributed support for this in https://github.com/hikari-no-yume/touchHLE/pull/34, merged in 32d12cc697f8fc62770962b8d5a1fee44dfba677. This will be in the next release. :)
