### ISSUE TITLE
add i18n?

### ISSUE THREAD

**Issue by GuihongWang** [hikari-no-yume/touchHLE#202]
add translate for appdb and app?and i try to re-sign(use my own keychain) the apk to upload th coolapk #180

and pull [touchhle](https://touchhle.org) to github repo? i try to clone it to gitee pages and translate it to chinese

**Comment by hikari-no-yume** [comment]
Why do you need to resign the APK?

**Comment by GuihongWang** [comment]
> Why do you need to resign the APK?

I misread their agreement because I used my own keychain when I certified the developer, so maybe I can do it without re-signing?

**Comment by GuihongWang** [comment]
> add translate for appdb and app? 
> and pull [touchhle](https://touchhle.org) to github repo? i try to clone it to gitee pages and translate it to chinese

?

**Comment by hikari-no-yume** [comment]
Regarding i18n, I understand the desire for it, but touchHLE really has a very minimal UI so I don't think it is very necessary. It is a large burden as a maintainer to have to worry about multiple languages. I do understand that it is unfriendly to people who don't understand English well, but I also think it is a manageable issue because touchHLE is not too hard to use. You are very welcome to make an unofficial translation of the README or the help text (`OPTIONS_HELP.txt`) if you want to, or write a Chinese tutorial. But I can't really add i18n support.

**Comment by GuihongWang** [comment]
> if you want to, or write a Chinese tutorial.
okey but how can i dock it to offical repo?

**Comment by nighto** [comment]
You can create a chinese version of the README file and open a PR to add it to the repository.

**Comment by hikari-no-yume** [comment]
No, please don't do that. I don't want to have to maintain a README in a language I don't speak.

**Comment by Davidliang11292** [comment]
> No, please don't do that. I don't want to have to maintain a README in a language I don't speak.

Hi, I'm from China, I think I can maintain README if you want (I don't have much time but I like to do this kind of thing)

**Comment by ciciplusplus** [comment]
@hikari-no-yume as you don't have plans to add i18n support or accept PRs, can we close this one?

**Comment by hikari-no-yume** [comment]
Yeah I think this is a wontfix.
