### ISSUE TITLE
IOS 3.X Games support

### ISSUE THREAD

**Issue by drpatrikking** [hikari-no-yume/touchHLE#26]
Hello. Did anyone tried running IOS 3.X games? And do they work?

**Comment by hikari-no-yume** [comment]
Hi. I know of at least two people who've run the emulator against many hundreds of apps for testing, and only Super Monkey Ball (an iPhone OS 2.0 game) works right now. I don't know how much effort iPhone OS 3 is going to be but I think it won't be a big problem.

This is such a broad topic that I am just going to close this issue, there's not a meaningful milestone that can be tied to it. Right now I don't think there's any value in tracking apps that _don't_ work, because the list is essentially infinite in length.

**Comment by upintheairsheep** [comment]
> Hi. I know of at least two people who've run the emulator against many hundreds of apps for testing, and only Super Monkey Ball (an iPhone OS 2.0 game) works right now. I don't know how much effort iPhone OS 3 is going to be but I think it won't be a big problem.
> 
> This is such a broad topic that I am just going to close this issue, there's not a meaningful milestone that can be tied to it. Right now I don't think there's any value in tracking apps that _don't_ work, because the list is essentially infinite in length.

Just a small suggestion, but can we make a way to execute all apps in a folder or something for testing and skip if it crashes? Sorry for being a bit demanding and noisy.

**Comment by hikari-no-yume** [comment]
You can probably achieve that using command-line scripting (e.g. batch files on Windows or bash scripts on Linux). I know some people have done this.
