### ISSUE TITLE
Dynarmic is removed

### ISSUE THREAD

**Issue by hmtheboy154** [hikari-no-yume/touchHLE#261]
Seems like the recent Yuzu takedown affect dynarmic too as of right now the github repo is down.

**Comment by hikari-no-yume** [comment]
The whole yuzu and citra situation has been very distressing to watch unfold. I know the author of dynarmic personally, so I'll ask her about it at some point. I'm going to lock discussion here until I know more. Not because I expect any legal issues, but because I worry there'll be uninformed speculation in these comments and I'd rather not see it.

**Comment by hikari-no-yume** [comment]
@ciciplusplus fixed in e7dc3eb13ed03e2eb4ff0c2f12993d5dbf667ffe
