### ISSUE TITLE
Black Screen Texture in Doom 2 RPG

### ISSUE THREAD

**Issue by MuzakyGood** [hikari-no-yume/touchHLE#278]
I'm playing TouchHLE v0.2.2 on android, and I found a bug Black Texture in the Doom 2 RPG . I have reached Ciscus
![Screenshot_20240403_062338_touchHLE.jpg](https://github.com/touchHLE/touchHLE/assets/112367361/ebea167d-61d1-430c-a8c2-5ea60c851f83)

My devices:
- Name Phone: Samsung A03
- Android Version: Android 13
- GPU: ARM Mali-G71 MP2, 770 MHz, Core 2, 64 Bit

**Comment by alborrajo** [comment]
Mind providing the game save data?

**Comment by omagadsamsa** [comment]
its bug 2 and 3 level

**Comment by omagadsamsa** [comment]
you can New save game

**Comment by MuzakyGood** [comment]
> you can New save game

Can it fix bugs? 
I want to finish this game. Previously I had successfully completed Wolfenstein RPG, Doom 1 Classic, and Crash Bandicot

**Comment by MuzakyGood** [comment]
> you can New save game

I am will wait for next bug fixed Update 👍

**Comment by alborrajo** [comment]
Should be fixed in the latest trunk

**Comment by xn117khdsh** [comment]
> Should be fixed in the latest trunk

Confirmed. The black texture is gone.

**Comment by MuzakyGood** [comment]
> Should be fixed in the latest trunk

I'm really looking forward to the next update  :D

**Comment by ciciplusplus** [comment]
Closing as fixed after https://github.com/touchHLE/touchHLE/commit/97dd7204e0f1d6b33435aa8279c0bc6865170fe9

**Comment by pepe9280** [comment]
I have the same problem

**Comment by alborrajo** [comment]
> I have the same problem

Which platform, version of the game and emulator version are you using? I've just tried on the latest trunk on Windows and it worked fine

**Comment by pepe9280** [comment]
Versión 2.2 and plataform tablet

**Comment by alborrajo** [comment]
> Versión 2.2 and plataform tablet

Version 2.2 is the one where the error was still happening. Although version 2.2 is the latest release, it's an old version (almost a year old), this issue is fixed in the code and will be fixed on the future version 2.3

If you don't want to wait until the new release you can install a preview build of the latest development, not only you won't have this issue but also you'll be able to play more games in it.

https://github.com/touchHLE/touchHLE/actions?query=branch%3Atrunk
