### ISSUE TITLE
Need to be located in touchHLE directory or cannot start

### ISSUE THREAD

**Issue by eisnerguy1** [hikari-no-yume/touchHLE#35]
So, it looks like you need to cd into the touchHLE directory or, you just get an error message and nothing will launch. Here's what I was getting when trying to run this command:

"/Users/eisnerguy1/Desktop/touchHLE_v0.1.0_macOS_x86_64/touchHLE /Users/eisnerguy1/Desktop/touchHLE_v0.1.0_macOS_x86_64/Versions/Super\ Monkey\ Ball\ \(v1.0.0\)/Monkey\ Ball.app --scale-hack=2 --y-tilt-offset=24"

"touchHLE v0.1.0 — https://touchhle.org/

thread 'main' panicked at 'Unexpected I/O failure when trying to access real path "touchHLE_dylibs/libstdc++.6.0.4.dylib": No such file or directory (os error 2). This might indicate that files needed by touchHLE are missing, or were moved while it was running.', src/fs.rs:275:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

If you cd into the "touchHLE_v0.1.0_macOS_x86_64" directory and run the command again, Super Monkey Ball launches. I'm running macOS 12.6.2.

**Comment by hikari-no-yume** [comment]
Hi. For legal and to some extent practical reasons, touchHLE has to put some fonts (`touchHLE_fonts`) and dynamic libraries (`touchHLE_dylibs`) in separate directories, rather than embedding them into the `.exe` file. So, it can't run from any directory, it needs to have those in the current directory. There's also a `touchHLE_sandbox` directory that's created when you run it, and that's used for your save games and other information stored by an app.

If this is a problem for you, I'd recommend writing a simple shell script that changes the current directory to the touchHLE one, runs touchHLE, and then returns back. I can help you out with that if you're unfamiliar with how.

This is a bit inconvenient of course. I could fall back to looking for these directories in the same directory that the touchHLE is in, but I think my preference for the moment is not to do that, I'm scared it'll get a bit messy.

**Comment by hikari-no-yume** [comment]
I think I'll consider this as a won't-fix for now. Happy for others to convince me otherwise.
