### ISSUE TITLE
Don't try to write in the installation directory

### ISSUE THREAD

**Issue by DCNick3** [hikari-no-yume/touchHLE#37]
While a point could be made for `touchHLE_fonts` and `touchHLE_dylibs` (it's not what you expect on Linux, but, it's not a center of the universe ig), I think writing to directories near the executable (like `touchHLE_sandbox`) is not something expected of desktop app nowadays.

If you install the app into a system-wide directory (like `C:\Program Files` or `/usr/share`), you can't really write there.

I recommend using `data_dir` function in [dirs-next](https://crates.io/crates/dirs-next) to locate a directory for your application data. This (usually, the os-specific logic is kinda complicated) corresponds to the following locations in different OSes:

- `C:\Users\Alice\AppData\Roaming` on Windows
- `/home/alice/.local/share` on Linux
- `/Users/Alice/Library/Application Support` on macOS

**Comment by hikari-no-yume** [comment]
Hmm… sorry to close this immediately, but for the time being I'm expecting this to be used in a “portable app” style, which is pretty common on Windows, and it's packaged in a way (zip file) that's ideal for that. I'll obviously reconsider this if or when it becomes common for it to be installed at the system level. One point against it right now is that, since it's pretty early days for this project, there could be quite a lot of release-to-release compatibility variation, so keeping multiple versions of it around and not having them clobber each other's user data (`touchHLE_sandbox`) is probably wise for now.
