### ISSUE TITLE
📱🕹️ The quest to relive iPhone OS games with touchHLE 🕹️📱

### ISSUE THREAD

**Issue by ferper04** [hikari-no-yume/touchHLE#56]
🚨"Uh, excuse me but where did my iPhone go?"🚨

So, I was just minding my own business, scrolling through my phone and then poof it disappeared into thin air! 🤔 But wait, it seems like I stumbled upon touchHLE and now I can run my fave iPhone apps on my desktop! 💻🎮

However, I have a serious question here. Why does touchHLE only support iPhone OS 2.x and not the newer versions? 🤔 Can't my iPhone 6s run on touchHLE too? 😢 And what about the iPad? Will it ever be supported? 💻🖥️

If anyone can shed some light on this situation, it would be greatly appreciated! 🙏 Until then, I'll be here waiting for a solution to my iPhone-less life. 📱👀

**Comment by parkerlreed** [comment]
This is still very much work in progress. Completely reverse engineering the way things works takes time. Down the line, later OS versions may be supported but there's no way to know for now.

**Comment by ferper04** [comment]
Ah gotcha! No worries, I totally understand that reverse engineering is a long and complicated process. Thanks for the update! I'll definitely keep an eye on this project and look forward to seeing the progress in the future. 🤞🤞

**Comment by ferper04** [comment]
Oh got it, thanks for the update! Can you give any rough estimate on when we might expect to see support for later iOS versions or is it still too early to say?

**Comment by hikari-no-yume** [comment]
Hi, author here.

> Why does touchHLE only support iPhone OS 2.x and not the newer versions?

There are two kinds of “unsupported”. There's things that the emulator can't do, and there's things that the emulator possibly could do, but which I don't make promises about, in order to manage expectations.

Strictly speaking, support for newer iOS versions is a mix of both. If we pick some numbers out of the air for the moment: an app whose minimum version is, say, iOS 6.0, probably will not work at all in touchHLE right now. On the other hand, there's a greater chance that an app whose minimum version is iPhone OS 3.0 might partially or even fully work, depending on exactly what it requires from the OS. The README says “Only iPhone/iPod touch apps for iPhone OS 2.x have been tested so far.” because I have made no attempt to support newer apps, I have not tested newer apps, and I do not expect newer apps to work.

[As elaborated on in the release announcement blog post](https://hikari.noyu.me/blog/2023-02-06-touchhle-anouncement-thread-tech-games-me-and-passion-projects.html), the original goal for this project was to run _Super Monkey Ball_. That's an iPhone OS 2.0 game. Therefore, iPhone OS 2.0 is the initial iOS version touchHLE tries to support.

At some point, I will run out of iPhone OS 2 apps I feel like prioritising, and I will start getting some iPhone OS 3 apps to work. At that point, I'll update the README to claim iPhone OS 3 support.

Likewise, at some point I'll at least _attempt_ to support iPhone OS 3.2, and then I'll attempt iOS 4, and so on. But each new OS version brings its own set of challenges, and it's quite possible that at some point (and I don't know what point that is), it doesn't seem worth the effort to support more versions.

Please bear in mind that this is a hobby project run by volunteers.

> Can't my iPhone 6s run on touchHLE too? And what about the iPad? Will it ever be supported?

touchHLE does not emulate the iPhone, iPod touch or iPad itself. touchHLE can run iPhone OS/iOS apps.

If you are wondering about support for iPad apps, the README addresses this.

**Comment by hikari-no-yume** [comment]
Oh, one more thing: the OS version is probably not the hurdle you should pay attention to. The fact this might eventually be able to run _a_ iOS 6 app, for example, does not mean it would be able to run _any_ iOS 6 app. It's probably never going to run every iPhone OS _2_ app, even.

**Comment by ferper04** [comment]
Hi hikari-no-yume,

Thanks for your question regarding touchHLE's support for newer iOS versions. As explained in the project's README and in your response, the emulator only supports iPhone OS 2.x apps at the moment because that was the initial goal of the project, and newer apps have not been tested. The developer plans to add support for newer iOS versions gradually but cannot guarantee that all apps will work due to the challenges that come with each new version.

Regarding your question about whether your iPhone 6s can run on touchHLE, it's worth noting that touchHLE does not emulate the iPhone, iPod touch, or iPad itself, but rather can run iPhone OS/iOS apps. As for iPad support, the README specifically addresses that as well.

Overall, it's important to keep in mind that touchHLE is a hobby project run by volunteers and is not meant to be a full-fledged emulator for all iOS apps. As such, while the developer plans to add support for newer iOS versions gradually, it's unlikely that touchHLE will be able to run every iPhone OS 2 or newer app.

**Comment by hikari-no-yume** [comment]
…are you a ChatGPT-based bot? go to hell
