### ISSUE TITLE
Map taps of any coordinate to inputs

### ISSUE THREAD

**Issue by childishbeat** [hikari-no-yume/touchHLE#64]
For instance, you could pause a game or use an item in Crash Bandicoot Nitro Kart 3D, all from the comfort of your own controller. There was an old app for jailbroken devices called Blutrol that could do this.

**Comment by hikari-no-yume** [comment]
Do you mean that you want to be able to press a button, and touchHLE would simulate tapping the screen in a particular location? I've thought about that. I'll add it at some point. I know some games will practically require this so it will definitely be added once I have to support one of those.

**Comment by childishbeat** [comment]
Yes.

**Comment by hikari-no-yume** [comment]
Just in case you missed it, you can already use the right analog stick to click on stuff, by using it to move the virtual cursor and then either pressing the stick itself or the right shoulder button. For me with my Xbox One controller this works well enough in Monkey Ball and Nitro Kart, but I'm aware some controllers have much worse analog sticks. I tried to navigate the Monkey Ball menu using Switch Joy-Cons and it was a nightmare.

**Comment by childishbeat** [comment]
I thought of that feature when I was writing this issue. The cursor's too fast for me and the self-centering's kinda weird, so there should be a setting for that, and to toggle it if needed.

**Comment by hikari-no-yume** [comment]
It's an absolute cursor rather than a relative one, which might be what's surprising you. Instead of the stick being used to make the cursor accelerate in a particular direction, the cursor's on-screen position is directly mapped to the stick's position. I need to tweak it a bit though, currently it uses a smaller part of the stick's range than it should.

**Comment by childishbeat** [comment]
I knew what to expect, so I'm not surprised. Just out of curiosity, why did you go with an absolute one?

**Comment by hikari-no-yume** [comment]
Well, the iPhone/iPod touch screen is pretty small, and since it's designed for touch input, the touch targets are usually pretty big, so I didn't think much precision was needed. Because the stick is spring-loaded to return to the centre, I could make the cursor only be visible when you're actively moving it, so I didn't need some other way to turn the cursor on and off, and it avoids obstructing your view of the game most of the time. If you have a sufficiently precise stick I think this is ideal for quickly “tapping” some large on-screen thing:

* Speeding up the level intro in Super Monkey Ball (tap anywhere near the center)
* Pausing in Super Monkey Ball (tap the timer)
* Jumping in Crash Bandicoot Nitro Kart 3D (tap anywhere near the center)
* Use an item in Crash Bandicoot Nitro Kart 3D (tap the item box)

But of course not everyone has as good a controller as the Xbox One controller, or good fine motor control in their hands for that matter.

Also, this system is not ideal for a game where you need to hold down your finger for a long time, or move it very precisely. For now the best solution for that is the mouse.

**Comment by hikari-no-yume** [comment]
> I need to tweak it a bit though, currently it uses a smaller part of the stick's range than it should.

Did this now: https://github.com/hikari-no-yume/touchHLE/commit/2cb68f07067726fb8a9c7874ad50d10c9b86fccf.

**Comment by hikari-no-yume** [comment]
I've now implemented the feature you want, I think: bbd1a90edf9d212e20edbbab0675253c0ffa1651. It's now possible to map A/B/X/Y to a location on the touch screen.

I haven't added any default mappings yet, but I'm considering it. For Crash Bandicoot, it would make sense to add ones for jumping, break/reverse, item use, and pausing.

**Comment by dante3732** [comment]
Should add stick emulation, so that pressing is a swipe from the center of the button to the sides.  And assigning buttons to the computer keyboard, not just the gamepad.

https://github.com/user-attachments/assets/48277fef-2800-4019-a2dc-e6b98c441193

In zombie infection, if you assign buttons to the edges of the stick, they don't work. You have to swipe and hold

**Comment by nighto** [comment]
@dante3732 While I think that the idea is valid, and somewhat related to this ticket, it is something else, that you should probably open a separate ticket for it.
