### ISSUE TITLE
Develop As LibRetro / RetroArch Core

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [hikari-no-yume/touchHLE#73]
Hi,

First of all, thanks for all of your efforts on this project! Some fantastic progress to-date!

I am aware that this project is in a fledgling state and there is still a lot of work to do to support other titles but, it would be great if the project could be forked and adapted to become a [LibRetro / RetroArch](https://www.libretro.com/index.php/api/) core. There are some benefits to doing this such a readily available GUI, baked in shader support, etc.

**Comment by hikari-no-yume** [comment]
Considering the horror stories I've heard from someone who works on a certain GameCube and Wii emulator, it sounds like libretro is really badly suited to consoles newer than maybe the SNES, and especially ones with as complex input needs as the Wii, or, let's assume, the iPhone. So alas this is probably going to be a “no” unless someone can convince me otherwise and is willing to do through the effort of porting it.

FWIW, I am going to add a GUI to touchHLE eventually, and it should be a controller-friendly experience etc.

**Comment by hikari-no-yume** [comment]
Considering the horror stories I've heard… it sounds like libretro is really badly suited to consoles newer than maybe the SNES, and especially ones with complex input methods, like the iPhone. So alas this is probably going to be a “no”.

FWIW, I am going to add a GUI to touchHLE eventually, and it should be a controller-friendly experience etc.

**Comment by hikari-no-yume** [comment]
I've also heard some worrying things about what it's like to interact with some of the people behind that project, so I feel like it might be best if I just avoid it.
