### ISSUE TITLE
Use standard config files

### ISSUE THREAD

**Issue by childishbeat** [hikari-no-yume/touchHLE#79]
The current TXT command-line system is less intuitive than a standard config file (e.g. CFG, CONF, INI). TXTs should be deprecated and still work or automatically converted.

**Comment by hikari-no-yume** [comment]
Well, my goals are different to what Microsoft's were for INI. I want per-app settings, and I don't want one file per app or one section per app. I also don't want to have two syntaxes for every setting: the command-line syntax and the config file syntax.

I'm sure this system is a bit unusual, but it's not any more complex than the alternatives, and I'm not currently convinced there's a real benefit to changing it.

The one thing I would like to change is to make it a bit easier to get a list of options, since I know using the command line is going to be frustrating for some.
