### ISSUE TITLE
if i want to participate this project, should i get an ios 2.x device?i am just a beginner of programming,but i am really interested in the ios emulator.

### ISSUE THREAD

**Issue by ghost** [hikari-no-yume/touchHLE#96]
if I want to participate in this project, should I get an ios 2. x device? I am just a beginner at programming, but I am really interested in the ios emulator.

**Comment by ghost** [comment]
could u send me the files of ios2 system？

**Comment by hikari-no-yume** [comment]
Having an old iPod touch, iPhone or perhaps iPad is useful so you can compare how an app runs on a real device to how it behaves in the emulator. You don't need iOS 2 really, I don't have an iOS 2 device myself. 

I can't send you the iOS system files since that probably falls under [the rule prohibiting piracy](https://github.com/hikari-no-yume/touchHLE/blob/trunk/CONTRIBUTING.md), but I'm not sure what use they'd be to you anyway. You can't really downgrade old iOS devices.
